language: julia
sudo: required
os:
  # - linux
  - osx
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
      - xauth
coveralls: true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(verbose=true)'
  - if [ `uname` = "Linux" ]; then
      xvfb-run julia --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true)';
    elif [ `uname` = "Darwin" ]; then
      julia --check-bounds=yes -e 'using Libdl; println(dllist())';
    fi
